apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: openmetadata-dependencies
    meta.helm.sh/release-namespace: default
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  creationTimestamp: "2025-03-16T11:53:26Z"
  labels:
    app.kubernetes.io/component: opensearch
    app.kubernetes.io/instance: openmetadata-dependencies
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/version: 2.7.0
    helm.sh/chart: opensearch-2.12.1
  name: opensearch-headless
  namespace: default
  resourceVersion: "812320"
  uid: e03ac6e5-39fb-4573-be4b-badea054918c
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: transport
    port: 9300
    protocol: TCP
    targetPort: 9300
  - name: metrics
    port: 9600
    protocol: TCP
    targetPort: 9600
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: openmetadata-dependencies
    app.kubernetes.io/name: opensearch
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---    
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: openmetadata-dependencies
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2025-03-16T11:53:26Z"
  labels:
    app.kubernetes.io/component: opensearch
    app.kubernetes.io/instance: openmetadata-dependencies
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/version: 2.7.0
    helm.sh/chart: opensearch-2.12.1
  name: opensearch
  namespace: default
  resourceVersion: "812333"
  uid: 7c15fbe5-7c59-4123-b7bd-81b283ec87d7
spec:
  clusterIP: 10.101.144.58
  clusterIPs:
  - 10.101.144.58
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: transport
    port: 9300
    protocol: TCP
    targetPort: 9300
  selector:
    app.kubernetes.io/instance: openmetadata-dependencies
    app.kubernetes.io/name: opensearch
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
