apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    majorVersion: "2"
    meta.helm.sh/release-name: openmetadata-dependencies
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2025-03-16T11:53:32Z"
  generation: 1
  labels:
    app.kubernetes.io/component: opensearch
    app.kubernetes.io/instance: openmetadata-dependencies
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/version: 2.7.0
    helm.sh/chart: opensearch-2.12.1
  name: opensearch
  namespace: default
  resourceVersion: "812428"
  uid: 9fca44c8-1e91-488f-ba05-0802c34e3648
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: openmetadata-dependencies
      app.kubernetes.io/name: opensearch
  serviceName: opensearch-headless
  template:
    metadata:
      annotations:
        configchecksum: e9acc41952a6fdae8a800efe4afe8b5d0df58d56f6f289d9744c7ce8f787644
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: opensearch
        app.kubernetes.io/instance: openmetadata-dependencies
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: opensearch
        app.kubernetes.io/version: 2.7.0
        helm.sh/chart: opensearch-2.12.1
      name: opensearch
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - openmetadata-dependencies
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - opensearch
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - env:
        - name: node.name
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: discovery.seed_hosts
          value: opensearch-cluster-master-headless
        - name: cluster.name
          value: opensearch
        - name: network.host
          value: 0.0.0.0
        - name: OPENSEARCH_JAVA_OPTS
          value: -Xmx1g -Xms1g
        - name: node.roles
          value: master,ingest,data,remote_cluster_client,
        - name: discovery.type
          value: single-node
        image: opensearchproject/opensearch:2.7.0
        imagePullPolicy: IfNotPresent
        name: opensearch
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        - containerPort: 9600
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 9200
          timeoutSeconds: 3
        resources:
          limits:
            cpu: "2"
            memory: 2048M
          requests:
            cpu: 100m
            memory: 256M
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
        startupProbe:
          failureThreshold: 30
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 9200
          timeoutSeconds: 3
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/opensearch/data
          name: opensearch
        - mountPath: /usr/share/opensearch/config/opensearch.yml
          name: config
          subPath: opensearch.yml
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      initContainers:
      - args:
        - chown -R 1000:1000 /usr/share/opensearch/data
        command:
        - sh
        - -c
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        name: fsgroup-volume
        resources: {}
        securityContext:
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/opensearch/data
          name: opensearch
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      terminationGracePeriodSeconds: 120
      volumes:
      - configMap:
          defaultMode: 420
          name: opensearch-config
        name: config
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: opensearch
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 30Gi
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  availableReplicas: 0
  collisionCount: 0
  currentReplicas: 1
  currentRevision: opensearch-9db4fc565
  observedGeneration: 1
  replicas: 1
  updateRevision: opensearch-9db4fc565
  updatedReplicas: 1
