apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: openmetadata-dependencies
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2025-03-16T11:53:26Z"
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: openmetadata-dependencies
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mysql
    helm.sh/chart: mysql-9.7.2
  name: mysql-headless
  namespace: default
  resourceVersion: "812319"
  uid: bc012d73-10bd-4009-a269-42fc394684b6
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: mysql
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: openmetadata-dependencies
    app.kubernetes.io/name: mysql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---    
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: openmetadata-dependencies
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2025-03-16T11:53:26Z"
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: openmetadata-dependencies
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mysql
    helm.sh/chart: mysql-9.7.2
  name: mysql
  namespace: default
  resourceVersion: "812339"
  uid: 8dd23a9c-a992-465e-b13c-3f264a2087e6
spec:
  clusterIP: 10.105.229.70
  clusterIPs:
  - 10.105.229.70
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: mysql
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: openmetadata-dependencies
    app.kubernetes.io/name: mysql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
