apiVersion: v1
data:
  LOG_LEVEL: SU5GTw==
  OPENMETADATA_CLUSTER_NAME: b3Blbm1ldGFkYXRh
kind: Secret
metadata:
  labels:
    app: openmetadata-config-secret
  name: openmetadata-config-secret
  namespace: default
type: Opaque
