apiVersion: v1
kind: Service
metadata:
  labels:
    service: openmetadata-app
  name: openmetadata-app
  namespace: default
spec:
  ports:
  - name: http
    port: 8585
    protocol: TCP
    targetPort: http
  - name: http-admin
    port: 8586
    protocol: TCP
    targetPort: http-admin
  selector:
    app: openmetadata-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
