apiVersion: v1
data:
  DB_CONNECTION_CHECK_CONNECTION_ON_BORROW: InRydWUi
  DB_CONNECTION_CHECK_CONNECTION_WHILE_IDLE: InRydWUi
  DB_CONNECTION_EVICTION_INTERVAL: IjUgbWludXRlcyI=
  DB_CONNECTION_MIN_IDLE_TIME: IjEgbWludXRlIg==
  DB_CONNECTION_POOL_INITIAL_SIZE: IjEwIg==
  DB_CONNECTION_POOL_MAX_SIZE: IjUwIg==
  DB_CONNECTION_POOL_MIN_SIZE: IjEwIg==
  DB_DRIVER_CLASS: Y29tLm15c3FsLmNqLmpkYmMuRHJpdmVy
  DB_HOST: bXlzcWw=
  DB_PARAMS: YWxsb3dQdWJsaWNLZXlSZXRyaWV2YWw9dHJ1ZSZ1c2VTU0w9ZmFsc2Umc2VydmVyVGltZXpvbmU9VVRD
  DB_PORT: MzMwNg==
  DB_SCHEME: bXlzcWw=
  DB_USER: b3Blbm1ldGFkYXRhX3VzZXI=
  OM_DATABASE: b3Blbm1ldGFkYXRhX2Ri
kind: Secret
metadata:
  labels:
    app: openmetadata-db-secret
  name: openmetadata-db-secret
  namespace: default
type: Opaque
